# Generated by Django 3.1.1 on 2020-09-30 19:42

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0003_auto_20200930_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
