# Generated by Django 3.1.1 on 2020-10-23 12:10

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0006_auto_20201021_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='completed',
        ),
        migrations.AlterField(
            model_name='issue',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Code'),
        ),
    ]
