# Generated by Django 3.1.1 on 2020-10-23 14:35

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0007_auto_20201023_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Body'),
        ),
    ]
